from pathlib import Path
p=Path(r'app/src/main/java/com/termux/app/CodexChatActivity.kt')
s=p.read_text(encoding='utf-8')
def rep(old,new,label):
 global s
 if old not in s: raise SystemExit(f'missing {label}')
 s=s.replace(old,new,1)
rep('''internal enum class NativeTurnPhase(val active: Boolean) {\n    IDLE(false), WAITING(true), REASONING(true), TOOL_RUNNING(true), ANSWERING(true), STOPPING(true), COMPLETED(false), FAILED(false)\n}\n\ninternal data class NativeAttachment''','''internal enum class NativeTurnPhase(val active: Boolean) {\n    IDLE(false), WAITING(true), REASONING(true), TOOL_RUNNING(true), ANSWERING(true), STOPPING(true), COMPLETED(false), FAILED(false)\n}\n\ninternal const val NATIVE_PROPOSED_PLAN_PREFIX = "PROPOSED_PLAN|"\ninternal fun encodeNativeProposedPlan(text: String): String = NATIVE_PROPOSED_PLAN_PREFIX + text\ninternal fun decodeNativeProposedPlan(content: String): String = content.substringAfter('|')\n\ninternal data class NativeAttachment''','constants')
rep('''    var planPanelAdded by mutableStateOf(false)\n    var revision by mutableIntStateOf(0)''','''    var planPanelAdded by mutableStateOf(false)\n    private var activeProposedPlanItemId = ""\n    var revision by mutableIntStateOf(0)''','active field')
rep('''        planPanelAdded = false\n        activeGoalObjective = ""''','''        planPanelAdded = false\n        activeProposedPlanItemId = ""\n        activeGoalObjective = ""''','reset')
rep('''.firstOrNull { messages[it].role == NativeChatRole.ASSISTANT }\n            ?: messages.size''','''.firstOrNull { messages[it].role == NativeChatRole.ASSISTANT || messages[it].content.startsWith(NATIVE_PROPOSED_PLAN_PREFIX) }\n            ?: messages.size''','ordering')
anchor='''    fun finishPlanPanel(stepCount: Int = 0) {\n'''
methods='''    private fun proposedPlanMessageId(itemId: String): String = "proposed-plan:${itemId.ifBlank { "current" }}"\n\n    private fun upsertProposedPlan(itemId: String, text: String, append: Boolean, streaming: Boolean) {\n        val resolvedItemId = itemId.ifBlank { activeProposedPlanItemId.ifBlank { "current" } }\n        activeProposedPlanItemId = resolvedItemId\n        val messageId = proposedPlanMessageId(resolvedItemId)\n        val existingIndex = messages.indexOfFirst { it.id == messageId && it.content.startsWith(NATIVE_PROPOSED_PLAN_PREFIX) }\n        val previous = if (existingIndex >= 0) decodeNativeProposedPlan(messages[existingIndex].content) else ""\n        val next = if (append) previous + text else text.ifEmpty { previous }\n        val message = NativeChatMessage(\n            id = messageId, role = NativeChatRole.ACTIVITY, content = encodeNativeProposedPlan(next), streaming = streaming,\n            revealStartedAt = if (existingIndex >= 0) messages[existingIndex].revealStartedAt else System.currentTimeMillis(),\n        )\n        if (existingIndex >= 0) messages[existingIndex] = message else messages.add(message)\n        phase = if (streaming) NativeTurnPhase.ANSWERING else phase\n        revision++\n    }\n\n    fun startProposedPlan(raw: String) {\n        val payload = runCatching { JSONObject(raw) }.getOrNull() ?: return\n        val item = payload.optJSONObject("item") ?: payload\n        upsertProposedPlan(item.optString("id", payload.optString("itemId")), item.optString("text"), false, true)\n    }\n\n    fun appendProposedPlanDelta(raw: String) {\n        val payload = runCatching { JSONObject(raw) }.getOrNull() ?: return\n        upsertProposedPlan(payload.optString("itemId", payload.optString("item_id")), payload.optString("delta"), true, true)\n    }\n\n    fun completeProposedPlan(raw: String) {\n        val payload = runCatching { JSONObject(raw) }.getOrNull() ?: return\n        val item = payload.optJSONObject("item") ?: payload\n        upsertProposedPlan(item.optString("id", payload.optString("itemId")), item.optString("text"), false, false)\n    }\n\n    private fun finishProposedPlanIfStreaming() {\n        val index = messages.indexOfLast { it.content.startsWith(NATIVE_PROPOSED_PLAN_PREFIX) && it.streaming }\n        if (index >= 0) messages[index] = messages[index].copy(streaming = false)\n    }\n\n'''
rep(anchor,methods+anchor,'methods')
rep('''.replace(Regex("""</?propose_plan\\s*>""", RegexOption.IGNORE_CASE), "")''','''.replace(Regex("""</?propose(?:d)?_plan(?:\\s[^>]*)?>""", RegexOption.IGNORE_CASE), "")''','regex')
rep('''    fun replaceHistory(value: String) {\n        val parsed = ArrayList<NativeChatMessage>()\n        planJson = "[]"\n        planExplanation = ""\n        val items = JSONArray(value)''','''    fun replaceHistory(value: String) {\n        val parsed = ArrayList<NativeChatMessage>()\n        val cachedPlanJson = planJson\n        val cachedPlanExplanation = planExplanation\n        var planPanelIndex = -1\n        planJson = "[]"\n        planExplanation = ""\n        planPanelAdded = false\n        activeProposedPlanItemId = ""\n        val items = JSONArray(value)''','history head')
rep('''                    planJson = planPayload.optJSONArray("plan")?.toString() ?: "[]"\n                    planExplanation = planPayload.optString("explanation")''','''                    planJson = planPayload.optJSONArray("plan")?.toString() ?: "[]"\n                    planExplanation = planPayload.optString("explanation")\n                    planPanelIndex = parsed.size''','history index')
rep('''        // One snapshot mutation avoids recomposing the chat once for every historical item.\n        messages.clear()''','''        if (planJson == "[]" && cachedPlanJson != "[]") {\n            planJson = cachedPlanJson\n            planExplanation = cachedPlanExplanation\n            planPanelIndex = parsed.size\n        }\n        if (planJson != "[]") {\n            val count = runCatching { JSONArray(planJson).length() }.getOrDefault(0)\n            parsed.add(planPanelIndex.coerceIn(0, parsed.size), NativeChatMessage(role = NativeChatRole.ACTIVITY, content = "PLAN_PANEL|complete|$count"))\n            planPanelAdded = true\n        }\n        // One snapshot mutation avoids recomposing the chat once for every historical item.\n        messages.clear()''','history panel')
rep('''    fun completeTurn() {\n        finishReasoning()\n        sealCurrentPhase()''','''    fun completeTurn() {\n        finishReasoning()\n        finishProposedPlanIfStreaming()\n        sealCurrentPhase()''','complete')
rep('''    private val pendingReasoning = StringBuilder()\n    private val pendingAnswer = StringBuilder()\n    private var reasoningFlushScheduled = false\n    private var answerFlushScheduled = false''','''    private val pendingReasoning = StringBuilder()\n    private val pendingAnswer = StringBuilder()\n    private val pendingPlan = StringBuilder()\n    private var pendingPlanItemId = ""\n    private var reasoningFlushScheduled = false\n    private var answerFlushScheduled = false\n    private var planFlushScheduled = false''','pending')
rep('''    private val flushAnswerRunnable = Runnable {\n        answerFlushScheduled = false\n        flushAnswerDeltas()\n    }\n    private var lastFrameNanos''','''    private val flushAnswerRunnable = Runnable {\n        answerFlushScheduled = false\n        flushAnswerDeltas()\n    }\n    private val flushPlanRunnable = Runnable {\n        planFlushScheduled = false\n        flushPlanDeltas()\n    }\n    private var lastFrameNanos''','runnable')
rep('''        getSharedPreferences("codex_mobile", MODE_PRIVATE).registerOnSharedPreferenceChangeListener(taskPreferenceListener)\n        refreshConversations()\n        startBackend()\n    }\n\n    private fun startBackend() {''','''        getSharedPreferences("codex_mobile", MODE_PRIVATE).registerOnSharedPreferenceChangeListener(taskPreferenceListener)\n        startRuntimeAfterFirstDraw()\n    }\n\n    private fun startRuntimeAfterFirstDraw() {\n        val decor = window.decorView\n        var scheduled = false\n        val listener = object : android.view.ViewTreeObserver.OnDrawListener {\n            override fun onDraw() {\n                if (scheduled) return\n                scheduled = true\n                decor.post {\n                    if (decor.viewTreeObserver.isAlive) decor.viewTreeObserver.removeOnDrawListener(this)\n                    if (isFinishing || isDestroyed) return@post\n                    refreshConversations()\n                    startBackend()\n                }\n            }\n        }\n        decor.viewTreeObserver.addOnDrawListener(listener)\n    }\n\n    private fun startBackend() {''','defer')
rep('''        Thread {\n            val enriched = snapshot.mapNotNull { task ->''','''        Thread {\n            val missingProjectIds = snapshot.asSequence().map { it.threadId }.filter { !conversationProjectCache.containsKey(it) }.toList()\n            if (missingProjectIds.isNotEmpty()) {\n                CodexAppServerBridge.resolveConversationProjects(missingProjectIds).forEach { (threadId, project) ->\n                    if (project.isNotBlank()) conversationProjectCache[threadId] = project\n                }\n            }\n            val enriched = snapshot.mapNotNull { task ->''','bulk head')
rep('''                val project = conversationProjectCache[task.threadId] ?: CodexAppServerBridge\n                    .resolveConversationProject(task.threadId)\n                    .also { resolved -> if (resolved.isNotBlank()) conversationProjectCache[task.threadId] = resolved }''','''                val project = conversationProjectCache[task.threadId].orEmpty()''','bulk use')
rep('''        streamHandler.removeCallbacks(flushReasoningRunnable)\n        streamHandler.removeCallbacks(flushAnswerRunnable)\n        reasoningFlushScheduled = false\n        answerFlushScheduled = false\n        val droppedReasoning = pendingReasoning.length\n        val droppedAnswer = pendingAnswer.length\n        pendingReasoning.setLength(0)\n        pendingAnswer.setLength(0)''','''        streamHandler.removeCallbacks(flushReasoningRunnable)\n        streamHandler.removeCallbacks(flushAnswerRunnable)\n        streamHandler.removeCallbacks(flushPlanRunnable)\n        reasoningFlushScheduled = false\n        answerFlushScheduled = false\n        planFlushScheduled = false\n        val droppedReasoning = pendingReasoning.length\n        val droppedAnswer = pendingAnswer.length\n        val droppedPlan = pendingPlan.length\n        pendingReasoning.setLength(0)\n        pendingAnswer.setLength(0)\n        pendingPlan.setLength(0)\n        pendingPlanItemId = ""''','discard')
rep('''.put("reason", reason).put("droppedReasoning", droppedReasoning).put("droppedAnswer", droppedAnswer))''','''.put("reason", reason).put("droppedReasoning", droppedReasoning).put("droppedAnswer", droppedAnswer).put("droppedPlan", droppedPlan))''','discard diag')
s=s.replace('''        NativeChatDiagnostics.record(this, "reasoning_flush", JSONObject()\n            .put("chars", value.length).put("total", chatState.reasoningText.length))\n''','',1)
s=s.replace('''        NativeChatDiagnostics.record(this, "answer_flush", JSONObject()\n            .put("chars", value.length).put("messages", chatState.messages.size))\n''','',1)
rep('''    override fun onEvent(function: String, value: String) {''','''    private fun flushPlanDeltas() {\n        streamHandler.removeCallbacks(flushPlanRunnable)\n        planFlushScheduled = false\n        if (pendingPlan.isEmpty()) return\n        val delta = pendingPlan.toString()\n        pendingPlan.setLength(0)\n        chatState.appendProposedPlanDelta(JSONObject().put("itemId", pendingPlanItemId).put("delta", delta).toString())\n    }\n\n    override fun onEvent(function: String, value: String) {''','flush plan')
handlers='''            "onPlanStarted" -> {\n                flushAnswerDeltas(); flushPlanDeltas(); chatState.finishReasoning(); chatState.startProposedPlan(value)\n            }\n            "onPlanDelta" -> {\n                flushAnswerDeltas(); chatState.finishReasoning()\n                val payload = runCatching { JSONObject(value) }.getOrNull()\n                val itemId = payload?.optString("itemId", payload.optString("item_id")).orEmpty()\n                val delta = payload?.optString("delta").orEmpty()\n                if (itemId.isNotBlank() && pendingPlanItemId.isNotBlank() && itemId != pendingPlanItemId) flushPlanDeltas()\n                if (itemId.isNotBlank()) pendingPlanItemId = itemId\n                if (delta.isNotEmpty()) pendingPlan.append(delta)\n                if (!planFlushScheduled && pendingPlan.isNotEmpty()) { planFlushScheduled = true; streamHandler.postDelayed(flushPlanRunnable, 56L) }\n            }\n            "onPlanComplete" -> {\n                flushAnswerDeltas(); flushPlanDeltas(); chatState.finishReasoning(); chatState.completeProposedPlan(value); pendingPlanItemId = ""\n            }\n'''
rep('''            "onPlanUpdated" -> {''',handlers+'''            "onPlanUpdated" -> {''','handlers')
rep('''            "onTurnComplete" -> {\n                flushReasoningDeltas()\n                flushAnswerDeltas()\n                chatState.completeTurn()''','''            "onTurnComplete" -> {\n                flushReasoningDeltas()\n                flushAnswerDeltas()\n                flushPlanDeltas()\n                chatState.completeTurn()\n                pendingPlanItemId = ""''','turn complete')
p.write_text(s,encoding='utf-8')
print('patched',len(s))
